### ISSUE TITLE
Subtitle addin failed

### ISSUE THREAD

**Issue by xszfqs** [sannies/mp4parser#125]
I wanna add a subtitle into a MP4,I tried to run your example(SubTitleExample),but there's something wrong with the step in setting builder.setFragmenter,the inc is always 0 so that it can't jump out the while circle.I'm sure the VTT file format is definitly right,and the MP4 is also nothing wrong.Can you help me find out the place that may have any mistake?Here I thank you in advance.

**Comment by xszfqs** [comment]
WEBVTT

00:00:01.000 --> 00:00:02.500
Je bent een eikel, Thom

this is my VTT file,I want to know if this file has something wrong.

Rogers

**Comment by sannies** [comment]
I updated the example to use a default Fragmenter instead of a custom one (what fails is just something I did for a local test). 
you can try my files: 
http://castlabs-dl.s3.amazonaws.com/public/dash.encrypt/testdata/tears_of_steel/Tears_Of_Steel_600000.mp4
http://castlabs-dl.s3.amazonaws.com/public/dash.encrypt/testdata/tears_of_steel/Tears_Of_Steel_128000_eng.mp4
http://castlabs-dl.s3.amazonaws.com/public/dash.encrypt/testdata/tears_of_steel/Tears_Of_Steel_eng.vtt
