### ISSUE TITLE
Lag at the end of a trimmed video on Moto X Android 5.0

### ISSUE THREAD

**Issue by SilkSama** [sannies/mp4parser#87]
Hello,
Firs of all thank you for your great job.
I have a problem when I trim a video on my moto X (2) phone on Android 5.0. A the end of each trimmed video there is a lag. I don't have the same problem on my nexus 4 on Android 5.0 too for example. 
Do you know a possible reason of this lag on this specific device (may be this lag occurs on other devices).
For information, I used your sample to short the video (SimpleShortenExample.java)
Thank you in advance for your answer.

**Comment by sannies** [comment]
A lag? That means the picture freezes for a moment or that the framerate drops? 
If you find the time it would interesting to see if the file from the Moto X also lags on the Nexus 4. When that's the case there is something wrong with the file otherwise with the device. Does the file that was shortened on the Nexus 4 lag on the Moto X? 
Please send me a file that's lagging. I'll have a look if there is something obviously wrong.

**Comment by sannies** [comment]
If you find the time to send me some files please do it (upload them to some hosting service such as dropbox as github issues won't accept attachment). I'll close the ticket for now. Feel free to re-open at any time.

**Comment by SilkSama** [comment]
Sorry for my late answer. The problem is not due to the mp4parser but it is due to the moto X phone. The lag occurs only on this phone (a trimmed video by the moto X has no lag on other phones). I have the same problem with non trimmed videos.
You can close the issue
Thx for your time
